services:
  fino_db:
    image: postgres:14.2
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: finotracker
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: fino_db
    volumes:
      - pgdata:/var/lib/posgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    depends_on:
      - fino_db

  # zeko-backend:
  #   build: .
  #   image: zeko-backend
  #   container_name: 'zeko-api'
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./zeko-backend:/zeko-backend

  #   env_file:
  #     - ./qricle/settings/.env
  #   depends_on:
  #     - db

volumes:
  pgdata:
