apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never # To avoid pulling the image from a remote registry
          ports:
            - containerPort: 8000
          env:
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: crypto-secrets
                  key: master-key
