apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never # To avoid pulling the image from a remote registry
          ports:
            - containerPort: 8000
          env:
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: crypto-secrets
                  key: master-key

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: auth-postgres
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: auth-service:latest
          imagePullPolicy: Never
          command: ["alembic", "upgrade", "head"]
          env:
            - name: POSTGRES_HOST
              value: auth-postgres
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: POSTGRES_PASSWORD
      restartPolicy: OnFailure
